### PR TITLE
Add pubip to piactl get command

### LINKED ISSUE #14: piactl get pubip
The `piactl` utility currently allows you to run `get vpnip` and it returns your VPN connected IP address. However, there is no apparent command to return your non-VPN public IP. If you're setup to pass everything through the VPN it's difficult to get your public IP address otherwise (unless you split-tunnel curl or something).

I would love it if there was a `piactl get pubip` command to go along with `vpnip` I assume this is possible given that the GUI client shows this.

### PR DESCRIPTION
**Pull request by MysticRyuujin**
**Description**
This changes adds `pubip` to `piactl get` CLI tool. It fixes #14 

**Checklist**
- [x] I have described below how to test my code and included unit tests where possible.
- [x] I have cleaned up the code and made best efforts to match the surrounding coding style.
- [x] I certify that I have the right to submit this contribution under the GPLv3 and alter as outlined in the [Contributor License Agreement](https://github.com/pia-foss/desktop/blob/master/CLA.md).

**Testing Plan**
I have built this change from source and verified that it returns the Public IP Address as displayed in the GUI

### CODE REVIEW

**Comment by JonathonH-PIA** [comment]
Nice work @MysticRyuujin !  Could you also hook up the appropriate change signal in `ValuePrinter::connectValueSignals()` (getcommand.cpp) so `piactl monitor pubip` works?

Also super minor - please tweak the description to sentence case, i.e. `Current public IP address` 😁 

We have a 2.4.0 in flight right now but I'd like to get this in our next release after that!  (Shouldn't be any conflicts)

**Comment by MysticRyuujin** [comment]
The reason I didn't add it to the `ValuePrinter::connectValueSignals` was that I couldn't determine what to hook it to...?

`vpnIp` hooks to  `&DaemonState::externalVpnIpChanged` but what would pubIp hook to?

**Comment by MysticRyuujin** [comment]
It looks like that should work, I found the definition of `externalVpnIpChanged` and there's a matching `externalIpChanged` :smile:

**Comment by JonathonH-PIA** [comment]
Great work, merging for next release!

**Pull request merged**
